# Generated by Django 3.2.16 on 2022-12-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221130_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('blocked', 'blocked'), ('admin', 'admin')], default='user', max_length=150, verbose_name='Заблокирован'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'user'), ('blocked', 'blocked'), ('admin', 'admin')], default='user', max_length=150, verbose_name='Роль'),
        ),
    ]
