# Generated by Django 3.2.16 on 2022-12-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221204_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='blocked',
        ),
    ]
