# Generated by Django 3.2.16 on 2022-12-02 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221201_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeingridient',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
