# Generated by Django 3.2.16 on 2022-12-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221203_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='C:\\Dev\\foodgram-project-react\\backend\\foodgram\\media/'),
        ),
    ]
