# Generated by Django 3.2.16 on 2022-12-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20221204_1951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingridient',
            new_name='Ingredient',
        ),
        migrations.RenameModel(
            old_name='RecipeIngridient',
            new_name='RecipeIngredient',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingridient_id',
            new_name='ingredient_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingridients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='api.RecipeIngredient', to='api.Ingredient'),
        ),
    ]
